name: Repository dispatch
on:
  repository_dispatch:
    types: [new-image]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: update image
        uses: mikefarah/yq@master
        with:
          cmd: yq eval '.spec.template.spec.containers[0].image = "${{ github.event.client_payload.image }}"' -i manifest/deployment.yaml

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply image name changes